### ISSUE TITLE
Custom exceptions?

### ISSUE THREAD

**Issue by fwkoch** [seequent/properties#159]
Currently, properties only uses builtin exceptions. `ValueError` when validation fails, `AttributeError` for setting invalid attribute, and `TypeError` when Property parameters are invalid. Custom exception types could improve error handling by separating properties errors from other unrelated Python errors. As long as they are subclassed correctly, there shouldn't be any backwards incompatibility issues.

**Comment by bsmithyman** [comment]
"As long as they are subclassed correctly" meaning we mix in `PropertiesError` or something like that with `ValueError` in the places where we normally use `ValueError`?

```python
class PropertiesError(Exception):
    """An exception in properties"""

class PropertiesValueError(ValueError, PropertiesError):
    "There are many like it, but this one is mine"""
```

Comme ça?

**Comment by fwkoch** [comment]
Yeah, that was exactly what I was thinking. That would also allow slightly more descriptive exceptions as well. Maybe instead of `PropertiesValueError` could do `PropertyValidationError`, `HasPropertiesValidationError`, etc.

**Comment by bsmithyman** [comment]
Yeah, that is a great idea. Like it a lot. And yeah, the more meaningful names are much better as you laid them out.

**Comment by fwkoch** [comment]
We now have custom validation errors which hold additional error info - https://github.com/seequent/properties/pull/224

For other non-validation errors, we will continue to use builtin python error types.
