### ISSUE TITLE
Question how to override `__init__` methods of `HasProperties` classes while maintaining picklability..

### ISSUE THREAD

**Issue by grosenkj** [seequent/properties#214]
I need to be able to override `__init__` method of the `HasProperties` classes that I am writing. I also require to be able to pickle the object. 

I would prefer to being able to explicitly declare arguments ( like `__init__(self, arg1, arg2,...)` ) that would correspond with the properties or assign the arguments to their respective properties.  but this will brake `pickle`. Below is a screen shot  example
![image](https://user-images.githubusercontent.com/6052367/35590347-71f8aa2c-05bb-11e8-8998-d3077a547282.png)

I have experimented with using keyword argument to be able to pickle objects but haven't had success with it. I attached a ipynb.txt version of the notebook I have been using. 

I would appreciate some guidance/discussion on best practice of overriding `__init__` methods of `HasProperties`, while being able to pickle the objects. I am not clear on how using arguments in the `__init__` method integrates with the `property` ecosystem, so if there true benefit to converting to keyword arguments I could be convinced.

Thanks, 

[PickleWork.ipynb.txt](https://github.com/aranzgeo/properties/files/1679329/PickleWork.ipynb.txt)

**Comment by fwkoch** [comment]
Hi @grosenkj - thanks for this issue, and sorry I left it unaddressed for so long. I just released a beta version of `properties` that refactors pickling. It removes the custom `__reduce__` and `__setstate__` code (these were what caused `__init__` to be called), and makes a few tweaks that prevent other minor pickling errors.

With these updates, your above code snippets seem to run fine. However, I do not have more complex use-cases for pickling. Do you mind updating to the beta version and seeing if this works for you?

`pip install properties==0.5.1b0`

**Comment by grosenkj** [comment]
@fwkoch Thanks for your reply. I have updated to the beta and so far things are working as expected which is super.

I will open a new issue if I run into any problems with this.

Thanks again.
