### ISSUE TITLE
pypi distribution versions

### ISSUE THREAD

**Issue by lheagy** [seequent/properties#247]
It looks like the version of `vectormath` distributes with the current `properties[math]` pypi deployment is `vectormath==0.1.4` (e.g. https://travis-ci.org/simpeg/simpeg/jobs/398867378#L2909). I would like to have SimPEG (and similar) running on the newest vectormath (0.2.0), but I can't seem to get this installing with properties. I tried installing `vectormath` and `properties` independently, but then ran into this [error](https://travis-ci.org/simpeg/simpeg/jobs/398849661#L2649)
```
error: vectormath 0.2.0 is installed but vectormath==0.1.4; extra == "math" is required by {'properties'}
``` 

Is there a way to easily have the most recent properties and the most recent vectormath install from pypi? (If not, I can move to installing from git, but would prefer to stick with pypi)

**Comment by fwkoch** [comment]
Thanks for catching this - I don't think there's any reason properties needs to be strict about this version number. I'll change the requirement to `vectormath>=0.1.4`. This should install the latest version by default, but still allow the previous version if desired.

**Comment by fwkoch** [comment]
Hopefully this solves your issues: https://github.com/seequent/properties/pull/249 - Let me know if you still have problems.

**Comment by lheagy** [comment]
Thanks @fwkoch! All is working 🎉
