### ISSUE TITLE
MRO bug on diamond inheritance

### ISSUE THREAD

**Issue by bsmithyman** [seequent/properties#275]
When inheriting from multiple classes that share a parent and override its properties, I expect each property to come from the first MRO entry that contains it. Instead, we seem to only be traversing one side of the multiple-inheritance diamond when reconstructing the `_props` dict. Interestingly, the selfdocs correctly identify where things should come from.

[reproduction.pdf](https://github.com/seequent/properties/files/3074416/reproduction.pdf)

So, actually both diamond subclasses are wrong. In one case, it’s subtle. In the other, we end up in a weird state where we have initializer code running, trying to somehow set a read-only prop, and causing an error.

**Comment by bsmithyman** [comment]
Docs are right, though:

```
Help on class AFirstMROChild in module __main__:

class AFirstMROChild(SubclassA, SubclassB)
 |  This is a subclass that prioritizes SubclassA over SubclassB
 |  
 |  **Required Properties:**
 |  
 |  * **some_string_prop**: This is some string prop, a unicode string
 |  
 |  **Other Properties:**
 |  
 |  * **some_integer_prop**: Some dynamic integer prop, an integer created dynamically
 |  
 |  Method resolution order:
 |      AFirstMROChild
 |      SubclassA
 |      SubclassB
 |      SomeBaseclass
 |      properties.base.base.HasProperties
 |      builtins.object
 |  
 |  Data descriptors inherited from SubclassA:
 |  
 |  some_integer_prop
 |      **some_integer_prop**: Some dynamic integer prop, an integer created dynamically
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from SubclassB:
 |  
 |  some_string_prop
 |      **some_string_prop**: This is some string prop, a unicode string, Default: Hello world!
 |  
```

```
Help on class BFirstMROChild in module __main__:

class BFirstMROChild(SubclassB, SubclassA)
 |  This is a subclass that prioritizes SubclassB over SubclassA
 |  
 |  **Required Properties:**
 |  
 |  * **some_integer_prop**: This is some integer prop, an integer
 |  * **some_string_prop**: This is some string prop, a unicode string, Default: Hello world!
 |  
 |  Method resolution order:
 |      BFirstMROChild
 |      SubclassB
 |      SubclassA
 |      SomeBaseclass
 |      properties.base.base.HasProperties
 |      builtins.object
 |  
 |  Data descriptors inherited from SubclassB:
 |  
 |  some_string_prop
 |      **some_string_prop**: This is some string prop, a unicode string, Default: Hello world!
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from SubclassA:
 |  
 |  some_integer_prop
 |      **some_integer_prop**: Some dynamic integer prop, an integer created dynamically
 |  
```

**Comment by fwkoch** [comment]
Thanks for this, @bsmithyman - The current implementation writes all properties on a class inside that class's `_props` dictionary, regardless of whether they were defined on the class or in a parent. So, in your example, `SubclassA` has `_props` (excuse the shorthand):
```
SubclassA._props = {
    some_integer_prop: DynamicProperty,
    some_string_prop: StringProperty with no default,
}
```
and `SubclassB`:
```
SubclassB._props = {
    some_integer_prop: IntegerProperty,
    some_string_prop: StringProperty with default,
}
```
For the diamond inheritance classes, in `AFirstMROChild` _both_ the values in `SubclassA._props` take precedence; in `BFirstMROChild` the `SubclassB._props` take precedence.

I attempted to fix this in #276 by taking the full `_props` dict from the most distant base, then for the intermediate bases, only updating prop values if they are redefined on the class (i.e. in `base.__dict__`). So, for example, with `AFirstMROChild` we start with `_props` from `SubclassB` (the most distant base), then we see only `some_integer_prop` is the only one that is redefined on `SubclassA`, so we only update that one.

Does that make sense? Getting into the metaclass is a bit hairy; likely that's a target for a major refactor at some point. But for now, this should be satisfactory. Let me know what you think of the #276

**Comment by bsmithyman** [comment]
Sweet, yeah, that makes sense. I was forgetting that we worked off of the most recent parent. Will test it out!

**Comment by bsmithyman** [comment]
Dumping this doc image in here so it doesn't get lost:

![image](https://user-images.githubusercontent.com/4269565/56139952-e3d26f00-5f67-11e9-8913-29c1338bdf16.png)
