### ISSUE TITLE
Coerce on Instance Property? 

### ISSUE THREAD

**Issue by lheagy** [seequent/properties#285]
Would including a `coerce` on an `Instance` property be of interest? I have an example where I am creating a `List` property of `Array` values, and would like to allow the user to simply input a list of numpy arrays, and we cast them to `properties.Array`. Right now, doing so causes a validation error. 

```python
locations = properties.List(
    "list of locations of each electrode in a dipole receiver",
    properties.Instance("electrode locations", properties.Array),
    min_length=1, max_length=2
)
```

The only mechanism from the outside that I would see to remedy this is to subclass `properties.Instance`? (other ideas appreciated!), which seems like a bit of overkill. 

Would something like the following seem suitable?
```python
locations = properties.List(
    "list of locations of each electrode in a dipole receiver",
    properties.Instance("electrode locations", properties.Array, coerce=True),
    min_length=1, max_length=2
)
```

**Comment by fwkoch** [comment]
Hey @lheagy - I think this might be slightly off track. An `Instance` of `properties.Array` will expect it to be a `Property` instance, not actually an array. I think what you are looking for is something like:

```python
class HasLocations(properties.HasProperties):
    
    locations = properties.List(
        'List of arrays',
        properties.Array(''),
        min_length=1,
        max_length=2,
    )
```

Then you can do this:
![image](https://user-images.githubusercontent.com/9453731/59906651-7bb86300-93c6-11e9-95d2-637dcd94b612.png)

`properties.List` has a `coerce` attribute that gives even more flexibility, like this:
![image](https://user-images.githubusercontent.com/9453731/59906771-c0dc9500-93c6-11e9-8289-420e7314e1bb.png)

That totally bypasses `Instance` and sounds like it fits your use case? If this isn't quite what you are looking for, please follow up! There _is_ a bit more you can do with `Instance` if necessary, but it would probably look more like `properties.Instance('', NumpyArraySubclass)` or something...

**Comment by lheagy** [comment]
Many thanks for the clarification @fwkoch!!
